### ISSUE TITLE
Save own Runes

### ISSUE THREAD

**Issue by DoisPontinhos** [2skydev/LADA#116]
Hey, would love to see a way to save my own runes/items and skill order for each champion

Keep up the good work

**Comment by 2skydev** [comment]
## LADA Code
https://github.com/2skydev/LADA/blob/main/src/main/modules/league/league.service.ts#L264
Set the runes and spells automatically in the 'triggerAutoSetting' method in the link above.

<br />

## LCU
You must use [LCU](https://riot-api-libraries.readthedocs.io/en/latest/lcu.html) to communicate with League of Legends (LADA communicates using the [league-connect](https://github.com/junlarsen/league-connect) library)

<br />

## Get Champion Statistics
Champion statistics such as items and rune builds are imported via external websites

<br />

## Summoner Spell Setting Example
https://github.com/2skydev/LADA/blob/c208d24e7ae5aed72b859bcb1d7cd52649f9eed7/src/main/modules/league/league.service.ts#L257-L260

<br />

## Rune Setting Example
https://github.com/2skydev/LADA/blob/c208d24e7ae5aed72b859bcb1d7cd52649f9eed7/src/main/modules/league/league.service.ts#L235-L240

**Comment by 2skydev** [comment]
If it's not the answer you wanted, please re-open the issue :)
