### ISSUE TITLE
Support English and more regions?

### ISSUE THREAD

**Issue by trangtiu** [2skydev/LADA#93]
Hi @2skydev ,
Can you update the Multilang features and add more regions?

**Comment by 2skydev** [comment]
Thank you for your opinion

If I have time, I will work on Korean and English first.

Other languages will receive a pull request.

**Comment by 2skydev** [comment]
Hello, the work has been completed, and we support i18n from v0.0.21.
https://github.com/2skydev/LADA/releases/tag/v0.0.21

If you're having problems with translation or want to add regions, please open PR or issues
Thank :D
